
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: amu-pulse-api
          config:
            - type: filestream
              id: amu-api-${data.docker.container.id}
              prospector.scanner.symlinks: true
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              parsers:
                - container:
                    stream: all
                    format: auto
                - ndjson:
                    target: ""
                    overwrite_keys: true
                    add_error_key: true
                    expand_keys: true

processors:
  - add_docker_metadata: ~
  - drop_fields:
      fields:
        - agent
        - ecs
        - input
        - docker
        - container.labels
        - host
      ignore_missing: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: amu-api-logs

setup.ilm:
  enabled: true
  policy_name: amu-api-logs
  policy_file: /usr/share/filebeat/ilm-policy.json
  overwrite: true

setup.template:
  name: amu-api-logs
  pattern: amu-api-logs
  overwrite: true
  settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0

setup.dashboards.enabled: false

logging.level: info
logging.to_files: false

monitoring.enabled: false
