"""assets sources and media baseline

Revision ID: 4a38e58a7011
Revises: 
Create Date: 2026-07-29 11:17:23.000550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import src.infra.postgres.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a38e58a7011'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_assets',
    sa.Column('created_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=55), nullable=False),
    sa.Column('code', sa.String(length=55), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tbl_media',
    sa.Column('created_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('backend', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('path')
    )
    op.create_table('tbl_sources',
    sa.Column('created_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=55), nullable=False),
    sa.Column('code', sa.String(length=55), nullable=False),
    sa.Column('website_url', sa.String(length=55), nullable=False),
    sa.Column('icon_url', sa.String(length=55), nullable=False),
    sa.Column('primary_color', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=55), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tbl_asset_configs',
    sa.Column('created_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduler_on', sa.Boolean(), nullable=False),
    sa.Column('scheduler_seconds', sa.Integer(), nullable=False),
    sa.Column('switch', sa.String(length=55), nullable=False),
    sa.Column('agg_type', sa.String(length=55), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['tbl_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_tbl_asset_configs_asset_id'), 'tbl_asset_configs', ['asset_id'], unique=False)
    op.create_table('tbl_source_configs',
    sa.Column('created_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('headers_credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auth_credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['tbl_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_tbl_source_configs_source_id'), 'tbl_source_configs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_source_configs_source_id'), table_name='tbl_source_configs')
    op.drop_table('tbl_source_configs')
    op.drop_index(op.f('ix_tbl_asset_configs_asset_id'), table_name='tbl_asset_configs')
    op.drop_table('tbl_asset_configs')
    op.drop_table('tbl_sources')
    op.drop_table('tbl_media')
    op.drop_table('tbl_assets')
    # ### end Alembic commands ###
