"""asset and symbol primary colour

Revision ID: f47cc75d3405
Revises: 1a518f62c3ca
Create Date: 2026-08-02 15:23:38.258227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import src.infra.postgres.types


# revision identifiers, used by Alembic.
revision: str = 'f47cc75d3405'
down_revision: Union[str, Sequence[str], None] = '98373ca62de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # a colour every existing row needs before the column can be NOT NULL;
    # the default goes away again so a new row has to bring its own
    op.add_column(
        'tbl_assets',
        sa.Column(
            'primary_color',
            sa.String(length=55),
            nullable=False,
            server_default='#c8a44b',
        ),
    )
    op.add_column(
        'tbl_symbols',
        sa.Column(
            'primary_color',
            sa.String(length=55),
            nullable=False,
            server_default='#c8a44b',
        ),
    )
    op.alter_column('tbl_assets', 'primary_color', server_default=None)
    op.alter_column('tbl_symbols', 'primary_color', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_symbols', 'primary_color')
    op.drop_column('tbl_assets', 'primary_color')
    # ### end Alembic commands ###
