"""bubbles and bubble configs

Revision ID: adfdb40ce6d5
Revises: 6ca77879a07c
Create Date: 2026-07-29 13:22:59.353145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import src.infra.postgres.types


# revision identifiers, used by Alembic.
revision: str = 'adfdb40ce6d5'
down_revision: Union[str, Sequence[str], None] = '6ca77879a07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_bubbles',
    sa.Column('created_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=55), nullable=False),
    sa.Column('title', sa.String(length=55), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tbl_bubble_configs',
    sa.Column('created_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', src.infra.postgres.types._TZDateTime(), server_default='NOW()', nullable=False),
    sa.Column('bubble_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduler_on', sa.Boolean(), nullable=False),
    sa.Column('scheduler_seconds', sa.Integer(), nullable=False),
    sa.Column('agg_type', sa.String(length=55), nullable=False),
    sa.ForeignKeyConstraint(['bubble_id'], ['tbl_bubbles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bubble_id')
    )
    op.create_index(op.f('ix_tbl_bubble_configs_bubble_id'), 'tbl_bubble_configs', ['bubble_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_bubble_configs_bubble_id'), table_name='tbl_bubble_configs')
    op.drop_table('tbl_bubble_configs')
    op.drop_table('tbl_bubbles')
    # ### end Alembic commands ###
